export const COUNTRY_LIST_REQUEST='COUNTRY_LIST_REQUEST'
export const COUNTRY_LIST_SUCCESS='COUNTRY_LIST_SUCCESS'
export const COUNTRY_LIST_FAIL='COUNTRY_LIST_FAIL'


export const DISTRICT_LIST_REQUEST='DISTRICT_LIST_REQUEST'
export const DISTRICT_LIST_SUCCESS='DISTRICT_LIST_SUCCESS'
export const DISTRICT_LIST_FAIL='DISTRICT_LIST_FAIL'


export const PROVINCE_LIST_REQUEST='PROVINCE_LIST_REQUEST'
export const PROVINCE_LIST_SUCCESS='PROVINCE_LIST_SUCCESS'
export const PROVINCE_LIST_FAIL='PROVINCE_LIST_FAIL'


export const LANGUAGE_LIST_REQUEST='LANGUAGE_LIST_REQUEST'
export const LANGUAGE_LIST_SUCCESS='LANGUAGE_LIST_SUCCESS'
export const LANGUAGE_LIST_FAIL='LANGUAGE_LIST_FAIL'


export const HAWALA_CURRENCY_LIST_REQUEST='HAWALA_CURRENCY_LIST_REQUEST'
export const HAWALA_CURRENCY_LIST_SUCCESS='HAWALA_CURRENCY_LIST_SUCCESS'
export const HAWALA_CURRENCY_LIST_FAIL='HAWALA_CURRENCY_LIST_FAIL'

export const HAWALA_BRANCH_LIST_REQUEST='HAWALA_BRANCH_LIST_REQUEST'
export const HAWALA_BRANCH_LIST_SUCCESS='HAWALA_BRANCH_LIST_SUCCESS'
export const HAWALA_BRANCH_LIST_FAIL='HAWALA_BRANCH_LIST_FAIL'


export const HELP_ARTICLE_LIST_REQUEST='HELP_ARTICLE_LIST_REQUEST'
export const HELP_ARTICLE_LIST_SUCCESS='HELP_ARTICLE_LIST_SUCCESS'
export const HELP_ARTICLE_LIST_FAIL='HELP_ARTICLE_LIST_FAIL'


